language: elixir

matrix:
  include:
    - otp_release: 19.0
      elixir: 1.4.0
    - otp_release: 19.3
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.5
    - otp_release: 20.0
      elixir: 1.6
    - otp_release: 20.3
      elixir: 1.7
    - otp_release: 20.3
      elixir: 1.8

sudo: false

script:
  - mix credo
